const accountScript=document.createElement('script');accountScript.src='account.js';accountScript.async=false;document.head.appendChild(accountScript);
const industries=[['manufacturing','산업 제조','工业制造'],['agri-food','농업·식품','农业食品'],['semiconductor','반도체·전자','半导体与电子'],['ai-robot','AI·로봇','人工智能与机器人'],['energy','신에너지','新能源'],['bio-health','바이오·헬스','生物医药'],['infrastructure','건설·인프라','建筑与基础设施'],['consumer','소비재·유통','消费品与零售'],['culture','문화·스포츠·관광','文化体育旅游']];
const saved=JSON.parse(localStorage.getItem('kctec-ko-market-prefs')||'{"regions":[],"industries":[]}');
const chosen={regions:new Set(saved.regions||[]),industries:new Set(saved.industries||[])};
document.getElementById('industries').innerHTML=industries.map(x=>`<button class="industry-chip ${chosen.industries.has(x[0])?'selected':''}" data-industry="${x[0]}"><b>${x[1]}</b><small>${x[2]}</small></button>`).join('');
const regionNames={northeast:'동북',north:'화북',southeast:'동남',southwest:'서남',northwest:'서북'};function updateSummary(){const rs=[...chosen.regions].map(x=>regionNames[x]).filter(Boolean),ins=[...chosen.industries].map(x=>industries.find(i=>i[0]===x)?.[1]).filter(Boolean);document.getElementById('selectionText').textContent=rs.length&&ins.length?`${rs.join('·')} × ${ins.join('·')}`:rs.length?`${rs.join('·')} 권역 선택됨`:ins.length?`${ins.join('·')} 산업 선택됨`:'권역과 산업을 선택하면 맞춤 뉴스가 구성됩니다.'}
function setupRegionMap(){const api=window.KCTEC_CHINA_REGIONS;if(!api)return;chosen.regions=new Set([...chosen.regions].filter(x=>api.groups[x]));
const paint=()=>{document.querySelectorAll('.region').forEach(b=>{const on=chosen.regions.has(b.dataset.region);b.classList.toggle('selected',on);b.setAttribute('aria-pressed',on)});
document.querySelectorAll('.china-province').forEach(p=>p.classList.toggle('selected',chosen.regions.has(p.dataset.region)));
const provinces=[...chosen.regions].flatMap(k=>api.groups[k].provinces.map(api.shortName));document.getElementById('provinceFeedback').textContent=provinces.length?`${provinces.length}개 성급 지역 선택: ${provinces.join('、')}`:'권역을 선택하면 포함된 성이 지도에 표시됩니다.';updateSummary()};
const toggle=k=>{chosen.regions.has(k)?chosen.regions.delete(k):chosen.regions.add(k);paint()};document.querySelectorAll('.region').forEach(b=>{b.onclick=()=>toggle(b.dataset.region);b.onmouseenter=()=>document.querySelectorAll(`.china-province[data-region="${b.dataset.region}"]`).forEach(p=>p.classList.add('group-hover'));b.onmouseleave=()=>document.querySelectorAll('.china-province').forEach(p=>p.classList.remove('group-hover'))});
document.querySelectorAll('.china-province').forEach(p=>{p.onclick=()=>toggle(p.dataset.region);p.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();toggle(p.dataset.region)}}});paint()}
document.addEventListener('china-map-ready',setupRegionMap,{once:true});if(window.KCTEC_CHINA_REGIONS)setupRegionMap();document.querySelectorAll('.industry-chip').forEach(b=>b.onclick=()=>{chosen.industries.has(b.dataset.industry)?chosen.industries.delete(b.dataset.industry):chosen.industries.add(b.dataset.industry);b.classList.toggle('selected');updateSummary()});updateSummary();
const setup=document.getElementById('preferenceSetup'),returnBar=document.getElementById('prefsReturn');function showPreferenceSetup(show){setup.hidden=!show;returnBar.hidden=show}showPreferenceSetup(localStorage.getItem('kctec-ko-market-prefs')===null);document.getElementById('editMarketPrefs').onclick=()=>{showPreferenceSetup(true);setup.scrollIntoView({behavior:'smooth',block:'start'})};document.getElementById('saveMarketPrefs').onclick=()=>{localStorage.setItem('kctec-ko-market-prefs',JSON.stringify({regions:[...chosen.regions],industries:[...chosen.industries]}));
const b=document.getElementById('saveMarketPrefs');b.textContent='저장되었습니다 ✓';setTimeout(()=>{b.textContent='관심 설정 저장';showPreferenceSetup(false)},650)};
const news=KCTEC_DATA.externalNews.filter(x=>x.channel==='china-tech').slice(0,3);document.getElementById('chinaNews').innerHTML=news.map((x,i)=>`<article class="cn-market-card" data-news="${x.id}"><img src="${x.image}" alt="${x.title_kr}"><div class="cn-card-body"><time>${x.date} · ${x.source}</time><h3>${x.title_kr}</h3><div class="cn-title" lang="zh-CN">${x.title_cn}</div><div class="cn-summary" lang="zh-CN">${x.points_cn.map((p,j)=>`<p>${j+1}. ${p}</p>`).join('')}</div><div class="news-actions"><button data-action="save">☆ 저장</button><button data-action="useful">◇ 유용함</button><button data-action="less">－ 줄이기</button><button data-action="ai">✨ AI 질문</button><button data-action="contact">✉ 센터 문의</button></div><div class="ai-box"><textarea placeholder="이 뉴스에 대해 궁금한 점을 남겨주세요…"></textarea><button data-send>AI에게 질문</button><div class="ai-answer"></div></div></div></article>`).join('');
const centerNews=KCTEC_DATA.associationNews.slice(0,3);document.getElementById('koCenterNews').innerHTML=centerNews.map(x=>`<a class="ko-center-card" href="association-news.html#n${x.id}"><img src="${x.image}" alt="${x.title_kr}"><div class="ko-center-copy"><time>${x.date} · ${x.category}</time><h3>${x.title_kr}</h3><p lang="zh-CN">${x.title_cn}</p><span>${x.brief_kr||''}</span><b>보도 보기 · 阅读报道 →</b></div></a>`).join('');
const football=KCTEC_DATA.enterpriseHistory.filter(x=>x.type==='football');document.getElementById('koFootball').innerHTML=football.map(x=>`<article class="ko-football-card"><img src="${x.image}" alt="${x.title_kr}"><div><time>${x.year}</time><h3>${x.title_kr}</h3><p lang="zh-CN">${x.title_cn}</p><span>${x.caption_kr||''}</span></div></article>`).join('');

document.addEventListener('click',e=>{const action=e.target.closest('[data-action]');if(!action)return;
const card=action.closest('.cn-market-card'),id=card.dataset.news;const toggle=()=>{action.classList.toggle('active');localStorage.setItem(`kctec-${action.dataset.action}-${id}`,action.classList.contains('active')?'1':'0');action.textContent=action.dataset.action==='save'?(action.classList.contains('active')?'★ 저장됨':'☆ 저장'):action.dataset.action==='useful'?(action.classList.contains('active')?'◆ 유용함 반영':'◇ 유용함'):(action.classList.contains('active')?'✓ 추천 감소':'－ 줄이기')};if(action.dataset.action==='save'){window.KCTEC_ACCOUNT?KCTEC_ACCOUNT.require(toggle):setTimeout(()=>KCTEC_ACCOUNT.require(toggle),200)}else if(['useful','less'].includes(action.dataset.action)){toggle()}else if(action.dataset.action==='ai'){card.querySelector('.ai-box').classList.toggle('open');card.querySelector('textarea').focus()}else{card.querySelector('.ai-box').classList.add('open');card.querySelector('textarea').value='이 프로젝트와 협력하고 싶습니다. 교류센터의 지원을 받을 수 있나요?';card.querySelector('textarea').focus()}});
document.addEventListener('click',e=>{if(!e.target.matches('[data-send]'))return;
const box=e.target.closest('.ai-box'),q=box.querySelector('textarea').value.trim();if(!q)return;box.querySelector('.ai-answer').innerHTML='<b>AI 시장 도우미</b><br>이 뉴스의 핵심은 중국의 기술 발전과 산업 협력 가능성입니다. 구체적인 참여 조건과 최신 정책은 원문 및 담당 기관을 추가 확인해야 합니다. 교류센터에 문의하면 관련 정보를 정리해 드릴 수 있습니다.'});
